ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "galleryImage1" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "galleryImage2" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "galleryImage3" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;
