ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3);
ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "usageLimit" INTEGER;
ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "usedCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "minOrder" DOUBLE PRECISION NOT NULL DEFAULT 0;
