ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "whatsapp" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "businessHours" TEXT;
ALTER TABLE "Restaurant" ADD COLUMN IF NOT EXISTS "institutionalText" TEXT;

ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
